# Generated by Django 4.0.5 on 2022-07-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('teamName', models.CharField(max_length=20)),
                ('dateOfBirth', models.CharField(max_length=30)),
                ('profilePic', models.ImageField(upload_to='shop/profilePic')),
                ('idProof', models.ImageField(upload_to='shop/idProof')),
                ('pass1', models.CharField(max_length=40)),
                ('pass2', models.CharField(max_length=40)),
            ],
        ),
    ]
