# Generated by Django 4.0.5 on 2022-07-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='idProof',
            field=models.ImageField(upload_to='idProof'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profilePic',
            field=models.ImageField(upload_to='profilePic'),
        ),
    ]
