# Generated by Django 4.0.5 on 2022-07-05 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_alter_userinfo_idproof_alter_userinfo_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='shiftAllotment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('serverName', models.CharField(max_length=15)),
                ('shiftTime', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
