# Generated by Django 4.0.5 on 2022-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_shiftallotment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftallotment',
            name='date',
            field=models.DateField(max_length=50),
        ),
    ]
