# Generated by Django 4.0.5 on 2022-07-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_shiftallotment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftallotment',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userinfo'),
        ),
    ]
