# Generated by Django 4.0.5 on 2022-07-07 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0006_alter_shiftallotment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftallotment',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
