# Generated by Django 4.0.5 on 2022-07-08 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0007_alter_shiftallotment_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='serverSheet',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('serverName', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=50)),
                ('shiftTime', models.CharField(max_length=50)),
                ('startingCount', models.IntegerField(blank=True, max_length=10)),
                ('endingCount', models.IntegerField(blank=True, max_length=10)),
                ('teamName', models.CharField(blank=True, max_length=50)),
                ('isghosted', models.CharField(blank=True, max_length=50)),
                ('isbonus', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
