# Generated by Django 4.0.5 on 2022-07-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_serversheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversheet',
            name='endingCount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='serversheet',
            name='startingCount',
            field=models.IntegerField(blank=True),
        ),
    ]
