# Generated by Django 4.0.5 on 2022-07-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_serversheet_endingcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftallotment',
            name='userName',
            field=models.CharField(max_length=50),
        ),
    ]
