# Generated by Django 4.0.5 on 2022-07-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_shiftallotment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversheet',
            name='userName',
            field=models.CharField(max_length=50),
        ),
    ]
