# Generated by Django 4.0.5 on 2022-07-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_serversheet_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversheet',
            name='endingCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serversheet',
            name='isbonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serversheet',
            name='isghosted',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serversheet',
            name='startingCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serversheet',
            name='teamName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
