# Generated by Django 4.0.5 on 2022-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_serversheet_endingcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversheet',
            name='commentText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
