# Generated by Django 4.0.5 on 2022-07-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_serversheet_commenttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversheet',
            name='endingCountScreenShot',
            field=models.ImageField(null=True, upload_to='endingingScreenShot'),
        ),
        migrations.AddField(
            model_name='serversheet',
            name='startingCountScreenShot',
            field=models.ImageField(null=True, upload_to='startingScreenShot'),
        ),
    ]
