# Generated by Django 4.0.5 on 2022-07-15 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_serversheet_endingcountscreenshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='screenShot',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('serverName', models.CharField(max_length=15)),
                ('shiftTime', models.CharField(max_length=50)),
                ('startingCountScreenShot', models.ImageField(default='', null=True, upload_to='startingScreenShot')),
                ('endingCountScreenShot', models.ImageField(default='', null=True, upload_to='endingingScreenShot')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='serversheet',
            name='endingCountScreenShot',
        ),
        migrations.RemoveField(
            model_name='serversheet',
            name='startingCountScreenShot',
        ),
    ]
