# Generated by Django 4.0.5 on 2022-07-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_screenshot_remove_serversheet_endingcountscreenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversheet',
            name='commentText',
            field=models.CharField(default='', max_length=500),
        ),
    ]
