# Generated by Django 4.0.5 on 2022-07-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_serversheet_commenttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversheet',
            name='approval',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
