# Generated by Django 4.0.5 on 2022-07-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_serversheet_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversheet',
            name='endingCountScreenShot',
            field=models.ImageField(default='', null=True, upload_to='endingingScreenShot'),
        ),
        migrations.AddField(
            model_name='serversheet',
            name='startingCountScreenShot',
            field=models.ImageField(default='', null=True, upload_to='startingScreenShot'),
        ),
    ]
