# Generated by Django 4.0.5 on 2022-07-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_serversheet_endingcountscreenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversheet',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
